services:
  code:
    build: .
    container_name: photography_blog
    tty: true
    ports:
      - 8000:8000
    volumes:
      - .:/code
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: db_app_local
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    