# Generated by Django 5.0.4 on 2024-05-02 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PictureMetadata",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("date", models.DateField()),
                ("iso", models.IntegerField()),
                ("shutter_speed", models.FloatField()),
                ("aperture", models.FloatField()),
                (
                    "lens_type",
                    models.CharField(
                        choices=[
                            ("SIGMA_16_28", "Sigma 16-28mm f/2.8"),
                            ("TAMRON_28_75", "Tamron 28-75 f/2.8"),
                            ("TAMRON_70_180", "Tamron 70-180 f/2.8 G2"),
                            ("SONY_200_600", "Sony 200-600 f/5.6-6.3 G OSS"),
                        ]
                    ),
                ),
                ("width", models.FloatField()),
                ("height", models.FloatField()),
                ("focal_length", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=32)),
                ("date", models.DateField()),
                ("location", models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name="Picture",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("s3_url", models.CharField(unique=True)),
                (
                    "extension",
                    models.CharField(
                        choices=[("jpg", "jpg"), ("jpeg", "jpeg"), ("arw", "arw")],
                        max_length=5,
                    ),
                ),
                (
                    "metadata",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="photography_blog.picturemetadata",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="photography_blog.session",
                        verbose_name="related session",
                    ),
                ),
            ],
        ),
    ]
